name       : haskell-transformers-compat
version    : 0.5.1.4
release    : 1
source     :
    - https://hackage.haskell.org/package/transformers-compat-0.5.1.4/transformers-compat-0.5.1.4.tar.gz : d881ef4ec164b631591b222efe7ff555af6d5397c9d86475b309ba9402a8ca9f
license    : BSD-3-Clause
component  : programming
summary    : This package includes backported versions of types that were added to transformers in transformers 0.3, 0.4, and 0.5 for users who need strict transformers 0.2 or 0.3 compatibility to run on old versions of the platform, but also need those types
description: |
    This package includes backported versions of types that were added to transformers in transformers 0.3, 0.4, and 0.5 for users who need strict transformers 0.2 or 0.3 compatibility to run on old versions of the platform, but also need those types
builddeps  :
    - ghc
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 transformers-compat-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/transformers-compat-$version.conf

