name       : haskell-transformers-compat
version    : 0.5.1.4
release    : 2
source     :
    - https://hackage.haskell.org/package/transformers-compat-0.5.1.4/transformers-compat-0.5.1.4.tar.gz : d881ef4ec164b631591b222efe7ff555af6d5397c9d86475b309ba9402a8ca9f
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package includes backported versions of types that were added to
    transformers in transformers 0.3, 0.4, and 0.5 for users who need strict transformers
    0.2 or 0.3 compatibility to run on old versions of the platform, but also need
    those types
description: |
    This package includes backported versions of types that were added to transformers in transformers 0.3, 0.4, and 0.5 for users who need strict transformers 0.2 or 0.3 compatibility to run on old versions of the platform, but also need those types
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
